<HTML>
<HEAD>
   <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=windows-1251">
   <META NAME="Author" CONTENT="Peter Anson">
   <META NAME="GENERATOR" CONTENT="Mozilla/4.05 [en] (Win95; I) [Netscape]">
   <META NAME="keywords" content="Flyers History Articles" >
   <META NAME="description" content="Flyers History Articles">
   <TITLE>Flyers History Articles</TITLE>
</HEAD>
<BODY TEXT=white BGCOLOR=black LINK=black VLINK=black ALINK=black BACKGROUND="/images/bg.jpg">
<img src="/images/main-articles.gif"><br><CENTER><table>
<tr><td onClick="window.location.href='https://www.philmyretalkshockey.com/blog-1/one-for-the-record'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='Phil Myre Reflects on 35 Game Streak';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="https://www.philmyretalkshockey.com/blog-1/one-for-the-record"  target="_parent"><font color=black size=-1>Phil Myre Reflects on 35 Game Streak</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.flyershistory.net/cgi-bin/aarticle.cgi?phillyhof2018'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='Reggie Leach Inducted Into Philly Sports Hall Of Fame';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.flyershistory.net/cgi-bin/aarticle.cgi?phillyhof2018"  target="_parent"><font color=black size=-1>Reggie Leach Inducted Into Philly Sports Hall Of Fame</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.wfmz.com/sports/flyers-pens-play-alumni-game-in-reading/402936235'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='March 18th Pens vs Flyers Alumni Game in Reading';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.wfmz.com/sports/flyers-pens-play-alumni-game-in-reading/402936235"  target="_parent"><font color=black size=-1>March 18th Pens vs Flyers Alumni Game in Reading</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.flyershistory.com/cgi-bin/photoalbum.cgi?nhsgame'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='NHS Celebrity Hockey Game';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.flyershistory.com/cgi-bin/photoalbum.cgi?nhsgame"  target="_parent"><font color=black size=-1>NHS Celebrity Hockey Game</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.flyershistory.net/cgi-bin/aarticle.cgi?stjohnsxmas2017'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='Flyers Aluni Visit St.John`s Hospice';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.flyershistory.net/cgi-bin/aarticle.cgi?stjohnsxmas2017"  target="_parent"><font color=black size=-1>Flyers Aluni Visit St.John`s Hospice</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.flyershistory.net/cgi-bin/aarticle.cgi?greatkid'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='An absolutely great kid';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.flyershistory.net/cgi-bin/aarticle.cgi?greatkid"  target="_parent"><font color=black size=-1>An absolutely great kid</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.flyershistory.com/cgi-bin/photoalbum.cgi?golfmeeting'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='2016 Flyers Alumni Golf Meeting Photos';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.flyershistory.com/cgi-bin/photoalbum.cgi?golfmeeting"  target="_parent"><font color=black size=-1>2016 Flyers Alumni Golf Meeting Photos</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.flyershistory.com/cgi-bin/photoalbum.cgi?2016alumnigolf'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='More 2016 Flyers Alumni Golf Tournament';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.flyershistory.com/cgi-bin/photoalbum.cgi?2016alumnigolf"  target="_parent"><font color=black size=-1>More 2016 Flyers Alumni Golf Tournament</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.flyershistory.com/cgi-bin/photoalbum.cgi?2016golf'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='2016 Flyers Alumni Golf Tournament';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.flyershistory.com/cgi-bin/photoalbum.cgi?2016golf"  target="_parent"><font color=black size=-1>2016 Flyers Alumni Golf Tournament</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.flyershistory.com/cgi-bin/photoalbum.cgi?macleishreview'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='MacLeish Review';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.flyershistory.com/cgi-bin/photoalbum.cgi?macleishreview"  target="_parent"><font color=black size=-1>MacLeish Review</font></a></td></tr>
<tr><td onClick="window.location.href='http://new.whl.ca/article/whl-top-50-players-of-all-time-countdown-concludes'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='Six Flyers named to Top 50 WHO Players Of All-Time';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://new.whl.ca/article/whl-top-50-players-of-all-time-countdown-concludes"  target="_parent"><font color=black size=-1>Six Flyers named to Top 50 WHO Players Of All-Time</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.flyersalumni.org/community/141-then-and-now-prolific-goal-scorer-leach-now-devoted-to-assisting-young-lives'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='Prolific Goal Scorer Leach Now Devoted to Assisting Young Lives ';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.flyersalumni.org/community/141-then-and-now-prolific-goal-scorer-leach-now-devoted-to-assisting-young-lives"  target="_parent"><font color=black size=-1>Prolific Goal Scorer Leach Now Devoted to Assisting Young Lives </font></a></td></tr>
<tr><td onClick="window.location.href='http://www.philly.com/philly/obituaries/20160601_Rick_MacLeish__smooth-skating__Cup-winning_Flyer__dies_at_66.html'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='Rick MacLeish Passes Away';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.philly.com/philly/obituaries/20160601_Rick_MacLeish__smooth-skating__Cup-winning_Flyer__dies_at_66.html"  target="_parent"><font color=black size=-1>Rick MacLeish Passes Away</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.manitoulin.ca/2016/05/20/reggie-leach-receive-order-manitoba/'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='Reggie Leach to receive the Order of Manitoba';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.manitoulin.ca/2016/05/20/reggie-leach-receive-order-manitoba/"  target="_parent"><font color=black size=-1>Reggie Leach to receive the Order of Manitoba</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.flyershistory.net/cgi-bin/aarticle.cgi?30yearclub'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='Flyers` 30 Year Club';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.flyershistory.net/cgi-bin/aarticle.cgi?30yearclub"  target="_parent"><font color=black size=-1>Flyers` 30 Year Club</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.philly.com/philly/sports/flyers/20160309_Flyers_founder_Ed_Snider_dies_at_83.html'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='Ed Snider Passes Away';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.philly.com/philly/sports/flyers/20160309_Flyers_founder_Ed_Snider_dies_at_83.html"  target="_parent"><font color=black size=-1>Ed Snider Passes Away</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.flyershistory.net/cgi-bin/aarticle.cgi?kadlecsnider'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='Kadlec and Snider - Together Since 1967';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.flyershistory.net/cgi-bin/aarticle.cgi?kadlecsnider"  target="_parent"><font color=black size=-1>Kadlec and Snider - Together Since 1967</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.flyershistory.net/cgi-bin/aarticle.cgi?stjoewomens2016'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='St.Joe`s Womens` Team';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.flyershistory.net/cgi-bin/aarticle.cgi?stjoewomens2016"  target="_parent"><font color=black size=-1>St.Joe`s Womens` Team</font></a></td></tr>
<tr><td onClick="window.location.href='http://www.flyershistory.net/cgi-bin/aarticle.cgi?stjoemens2016'" onMouseOver="this.style.backgroundColor='#DD3300'; window.status='St.Joe`s Mens` Team';return true;" onMouseOut="this.style.backgroundColor='#AAAAAA'; window.status='';" bgcolor="#AAAAAA" align="center" height=13 width=450><a href="http://www.flyershistory.net/cgi-bin/aarticle.cgi?stjoemens2016"  target="_parent"><font color=black size=-1>St.Joe`s Mens` Team</font></a></td></tr>
</table><br><a href="/cgi-bin/allarticles.cgi" target="_parent"><font color=white>Click here all articles</font></a></center></BODY></HTML>
</center></BODY></HTML>
